### ISSUE TITLE
POST

### ISSUE THREAD

**Issue by renans04** [renans04/OzMap#1]
### Estou recebendo o devido erro:

> TypeError: Cannot destructure property 'nome' of 'ctx.body' as it is undefined.

### Código

`post('/create', async (ctx) => { 
  try {
    const { nome, email, idade } = ctx.body
    console.log(`${nome}`)
    await schema.create(
      {
        nome,
        email,
        idade
      }
    )
  } catch (error) {
    console.log(error)
  }
})`

**Meu objetivo é inserir novos usuários no banco de dados.**

**Comment by raupp** [comment]
antes de qlqr coisa, tenta fazer um:
post('/create', async (ctx) => { 
console.log(ctx.body)
console.log(ctx.parameters)
console.log(ctx.query)
}
Para ver o que está recebendo como parte do request.
PS: na base do projeto, não foi adicionado um middleware ( bodyparser/busyboy) para tratar o dado do body.

**Comment by renans04** [comment]
Entendi como funciona o bodyParser, utilizei o mesmo para resolver o meu problema. Muito Obrigado.
